### ISSUE TITLE
Simple Moving Average C++ Implementation Error?

### ISSUE THREAD

**Issue by kuoky** [tttapa/tttapa.github.io#10]
On your hompage:
https://tttapa.github.io/Pages/Mathematics/Systems-and-Control-Theory/Digital-filters/Simple%20Moving%20Average/C++Implementation.html

SMA is returned as:
`return (sum + (N / 2)) / N;`

Why `+ (N / 2)`?  Shouldn't it be just `return (sum / N)` ?

**Comment by tttapa** [comment]
`sum / N` would be a flooring division, `(sum + N/2) / N` is a rounding division for unsigned integers.

For different data types, have a look at https://github.com/tttapa/Arduino-Filters/blob/master/src/AH/Math/Divide.hpp.

**Comment by kuoky** [comment]
Ah, okay. Thanks!
