### ISSUE TITLE
studies

### ISSUE THREAD

**Issue by edmanferson** [tttapa/tttapa.github.io#16]
hello, can you make the python code available for the worksheet ''The damped harmonic oscillator"?
https://tttapa.github.io/Pages/Arduino/Audio-and-Signal-Processing/VU-Meters/Damped-Harmonic-Oscillator.html

**Comment by tttapa** [comment]
Which Python code are you referring to? All code should be available through the _“Image source code”_ links under the figures.

**Comment by edmanferson** [comment]
> A qual código Python você está se referindo? Todo o código deve estar disponível através dos links _“Código fonte da imagem”_ abaixo das figuras.

**Comment by edmanferson** [comment]
Thank you very much, I can see the code.
